### ISSUE TITLE
Incompatible with Obscure API

### ISSUE THREAD

**Issue by Karashok-Leo** [SpaceCat97/SpaceCats-Wikis#13] opened 2024-02-06 14:04 UTC
When I install both ASB and Obscure API at the same time, the tooltip of ASB cannot be displayed properly.

**Comment by SpaceCat97** [comment] 2024-02-06 14:08
Are you sure it is the api? Could it be their tooltips mod that causes the issue?

**Comment by Karashok-Leo** [comment] 2024-02-06 14:10
> Are you sure it is the api? Could it be their tooltips mod that causes the issue?

They should have done something about tooltip. I'm not sure because both sides are closed source.

**Comment by SpaceCat97** [comment] 2024-02-06 14:11
I am speaking about this mod - https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips

if you remove it from your pack, does it still break?

**Comment by Karashok-Leo** [comment] 2024-02-06 14:23
> I am speaking about this mod - https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips
> 
> if you remove it from your pack, does it still break?

I did not install obscure-tooltips, only the API. I have repeatedly confirmed it.
I also posted an issue in their discord.

**Comment by SpaceCat97** [comment] 2024-02-06 14:24
Thank you for confirming. I will see if I can solve anything on my end.

**Comment by SpaceCat97** [comment] 2024-02-06 14:35
I have just tested ASB with Obscure API installed. It worked with no issues at all.

Please find the root cause of your problem. Only then will I be able to help you.
![2024-02-06_14 33 54](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/12462443/bde7e133-8644-4118-866d-008bae6fdca4)

**Comment by Karashok-Leo** [comment] 2024-02-06 14:55
[latest.log](https://github.com/SpaceCat97/SpaceCats-Wikis/files/14181932/latest.log)
I checked again, but there is still a problem.
mods:
	- architectury 9.1.12
	- fabric-api 0.90.7+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577.......
	- fabricloader 0.14.24
	- java 20
	- minecraft 1.20.1
	- obscure_api 16
	- spacecatasb 20.10.1

> I have just tested ASB with Obscure API installed. It worked with no issues at all.
> 
> Please find the root cause of your problem. Only then will I be able to help you. ![2024-02-06_14 33 54](https://private-user-images.githubusercontent.com/12462443/302665215-bde7e133-8644-4118-866d-008bae6fdca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzA0MjYsIm5iZiI6MTcwNzIzMDEyNiwicGF0aCI6Ii8xMjQ2MjQ0My8zMDI2NjUyMTUtYmRlN2UxMzMtODY0NC00MTE4LTg2NmQtMDA4YmFlNmZkY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE0MzUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NDIxOGE1YjQ5NGIyYmU1Y2JkZjU1NDM1N2I0NTA4MWJlZWE1MGZiY2IxMGNhNjcxOGU0NDA1Y2Q4NWJmNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tYqZAZMWhWKtzPMTEj8kWITNiudSgkVmnCMG1mP3oUA)

**Comment by Karashok-Leo** [comment] 2024-02-06 15:31
![2024-02-06_22 50 21](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/139102377/0ee47d8a-49bb-4bc3-aa13-6da4590f316e)
![2024-02-06_22 51 16](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/139102377/58506ee1-417e-410d-a19d-71097a07ab66)
The two images show the effects before and after installing Obscure  API.

**Comment by SpaceCat97** [comment] 2024-02-06 16:18
I tested on forge, your issue is on fabric. My mod adds tooltips by injecting into the ItemTooltipEvent for forge.

For fabric, my mod uses a mixin to inject into the getTooltipLines method and add entries to the Component List. I am not sure how obscure api does this but they probably also mess with that method which breaks my mod.

I am looking into another way to register tooltips for fabric which will hopefully fix this issue. The potential fix will be released in the next 1.20 version of this mod.

**Comment by Karashok-Leo** [comment] 2024-02-06 16:39
> I tested on forge, your issue is on fabric. My mod adds tooltips by injecting into the ItemTooltipEvent for forge.
> 
> For fabric, my mod uses a mixin to inject into the getTooltipLines method and add entries to the Component List. I am not sure how obscure api does this but they probably also mess with that method which breaks my mod.
> 
> I am looking into another way to register tooltips for fabric which will hopefully fix this issue. The potential fix will be released in the next 1.20 version of this mod.

Thank you for your patience. But fabric API provides an event related to tooltips, why not use it (just out of curiosity)

**Comment by SpaceCat97** [comment] 2024-02-06 16:42
Originally I did a mixin because the fabric event does not pass the player object through. I have an idea that may work.

**Comment by Karashok-Leo** [comment] 2024-02-06 16:45
> Originally I did a mixin because the fabric event does not pass the player object through. I have an idea that may work.

Got it. thx

**Comment by SpaceCat97** [comment] 2024-02-06 16:50
Just managed to change the way tooltips are registered on fabric, you can expect to see this fix in the next version 1.20+ **only**

**Comment by SpaceCat97** [comment] 2024-02-06 22:52
Fix applied to 20.11.0

**Closed by SpaceCat97** 2024-02-06 22:52 UTC
Labels: bug, ASB, improvement, accepted
